#make file

all: #target name
	1 2 3 4 5
1:
	gcc -Wall 5.1.c -o 5.1
2:
	gcc -Wall ue52_stub.c -o 5.2
3:
	gcc -Wall ue53_stub.c -o 5.3
4:
	gcc -Wall ue54_stub.c -o 5.4
5:
	gcc -Wall ue55.c -o 5.5


clean:
	rm 5.1 5.2 5.3 5.4 5.5